### PR TITLE
Adding params for PE

### PR DESCRIPTION
**Pull request by jolshevski**
The config file owner should be set to puppet on POSS and pe_puppet on Puppet Enterprise.  This fix allows users to pass group and owner as class params that default to the open source values.

### CODE REVIEW

**Comment by jlambert121** [comment]
@jolshevski what do you think about #9?  This way there shouldn't be any configuration needed for either puppet project.

**Comment by jolshevski** [comment]
I like it.  What do you think about abstracting it out of the default class using the params pattern like this?

**Comment by jlambert121** [comment]
Funny - I apparently didn't scroll all of the way down, all I saw was your changes to the init.pp.  Yours is better, if you rebase on master I think that will fix the tests and I can merge it.

**Comment by jolshevski** [comment]
Do you care about the strict variables tests?  They're failing but the rest of the matrix is passing.

**Comment by jlambert121** [comment]
Yeah, but I can fix it - no worries.  Thanks for the contribution!

**Comment by jlambert121** [comment]
0.3.0 has been pushed to the forge

**Pull request merged**
